#!/bin/bash
# HTTP Proxy installation using Squid

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$SCRIPT_DIR/lib/utils.sh"
. "$SCRIPT_DIR/lib/pkg.sh"
. "$SCRIPT_DIR/lib/firewall.sh"

install_http_proxy() {
    local port="$1"
    local username="$2"
    local password="$3"
    local pkg_manager="$4"
    
    info "Bắt đầu cài đặt HTTP Proxy (Squid)..."
    
    # Validate inputs
    if ! validate_port "$port"; then
        return 1
    fi
    
    if is_port_in_use "$port"; then
        error "Port $port đang được sử dụng"
        return 1
    fi
    
    if ! validate_username "$username"; then
        return 1
    fi
    
    if ! validate_password "$password"; then
        return 1
    fi
    
    # Install squid
    local squid_pkg="squid"
    if ! check_package_available "$pkg_manager" "$squid_pkg"; then
        error "Package squid không có sẵn trên distro này"
        return 1
    fi
    
    install_packages "$pkg_manager" "$squid_pkg" || return 1
    
    # Install htpasswd tool
    local htpasswd_pkg=""
    case "$pkg_manager" in
        apt|apt-get)
            htpasswd_pkg="apache2-utils"
            ;;
        yum|dnf)
            htpasswd_pkg="httpd-tools"
            ;;
    esac
    
    if [ -n "$htpasswd_pkg" ]; then
        install_packages "$pkg_manager" "$htpasswd_pkg" || {
            warn "Không thể cài apache2-utils/httpd-tools. Sẽ tạo password file thủ công."
        }
    fi
    
    # Create password file directory
    local passwd_dir="/etc/squid"
    mkdir -p "$passwd_dir"
    
    # Create password file
    local passwd_file="$passwd_dir/passwords"
    
    if command -v htpasswd >/dev/null 2>&1; then
        # Create new password file
        echo "$password" | htpasswd -ci "$passwd_file" "$username" 2>/dev/null || {
            error "Không thể tạo password file với htpasswd"
            return 1
        }
        ok "Đã tạo password file"
    else
        # Fallback: use openssl to create htpasswd format
        warn "htpasswd không có sẵn, sử dụng openssl..."
        local hash=$(openssl passwd -apr1 "$password" 2>/dev/null || echo "")
        if [ -z "$hash" ]; then
            error "Không thể tạo password hash"
            return 1
        fi
        echo "$username:$hash" > "$passwd_file"
        chmod 600 "$passwd_file"
        ok "Đã tạo password file với openssl"
    fi
    
    # Backup original config
    local squid_conf="/etc/squid/squid.conf"
    if [ -f "$squid_conf" ]; then
        cp "$squid_conf" "${squid_conf}.backup.$(date +%Y%m%d_%H%M%S)"
    fi
    
    # Create Squid configuration
    cat > "$squid_conf" <<EOF
# Auto-generated by auto-proxy-installer
# HTTP Proxy Configuration

# Basic settings
http_port $port
visible_hostname localhost

# Authentication
auth_param basic program /usr/lib/squid/basic_ncsa_auth $passwd_file
auth_param basic children 5
auth_param basic realm Squid Proxy
auth_param basic credentialsttl 2 hours

# ACLs
acl authenticated proxy_auth REQUIRED
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16

# Access rules
http_access allow authenticated
http_access deny all

# Logging
access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log

# Disable caching for proxy
cache deny all
EOF
    
    # Create log directory
    mkdir -p /var/log/squid
    chown -R proxy:proxy /var/log/squid 2>/dev/null || chown -R squid:squid /var/log/squid 2>/dev/null || true
    
    # Set permissions
    chmod 600 "$passwd_file"
    chown root:root "$passwd_file"
    
    # Open firewall port
    open_firewall_port "$port" "tcp"
    
    # Enable and start service
    systemctl daemon-reload
    systemctl enable squid
    if systemctl restart squid; then
        ok "Đã khởi động Squid service"
    else
        error "Không thể khởi động Squid service"
        error "Kiểm tra log: journalctl -u squid -n 50"
        return 1
    fi
    
    # Save state
    save_proxy_state "http" "$port" "$username" "$password"
    
    ok "HTTP Proxy đã được cài đặt thành công!"
    return 0
}

save_proxy_state() {
    local proxy_type="$1"
    local port="$2"
    local username="$3"
    local password="$4"
    
    local state_dir="/etc/auto-proxy-installer"
    mkdir -p "$state_dir"
    
    # Use a simple approach: append to a text file (don't save password)
    local simple_state="$state_dir/installed_proxies.txt"
    echo "$proxy_type|$port|$username|$(date +%Y-%m-%d)" >> "$simple_state"
}

get_proxy_state() {
    local simple_state="/etc/auto-proxy-installer/installed_proxies.txt"
    if [ -f "$simple_state" ]; then
        cat "$simple_state"
    fi
}

