#!/bin/bash
# SOCKS5 Proxy installation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$SCRIPT_DIR/lib/utils.sh"
. "$SCRIPT_DIR/lib/pkg.sh"
. "$SCRIPT_DIR/lib/firewall.sh"

install_socks5_proxy() {
    local port="$1"
    local username="$2"
    local password="$3"
    local pkg_manager="$4"
    
    info "Bắt đầu cài đặt SOCKS5 Proxy..."
    
    # Validate inputs
    if ! validate_port "$port"; then
        return 1
    fi
    
    if is_port_in_use "$port"; then
        error "Port $port đang được sử dụng"
        return 1
    fi
    
    if ! validate_username "$username"; then
        return 1
    fi
    
    if ! validate_password "$password"; then
        return 1
    fi
    
    # Try to install dante-server first
    local use_dante=false
    local dante_pkg=""
    
    case "$pkg_manager" in
        apt|apt-get)
            dante_pkg="dante-server"
            ;;
        yum|dnf)
            dante_pkg="dante"
            ;;
    esac
    
    if [ -n "$dante_pkg" ] && check_package_available "$pkg_manager" "$dante_pkg"; then
        info "Tìm thấy dante-server, đang cài đặt..."
        if install_packages "$pkg_manager" "$dante_pkg"; then
            use_dante=true
        fi
    fi
    
    if [ "$use_dante" = true ]; then
        install_socks5_dante "$port" "$username" "$password" "$pkg_manager"
    else
        warn "Dante-server không có sẵn, sử dụng microsocks..."
        install_socks5_microsocks "$port" "$username" "$password" "$pkg_manager"
    fi
}

install_socks5_dante() {
    local port="$1"
    local username="$2"
    local password="$3"
    local pkg_manager="$4"
    
    info "Cài đặt SOCKS5 với Dante-server..."
    
    # Create user if not exists
    if ! id "$username" >/dev/null 2>&1; then
        useradd -r -s /bin/false "$username" || {
            error "Không thể tạo user $username"
            return 1
        }
    fi
    
    # Set password for user
    echo "$username:$password" | chpasswd || {
        error "Không thể set password cho user"
        return 1
    }
    
    # Backup original config
    local dante_conf="/etc/danted.conf"
    if [ -f "$dante_conf" ]; then
        cp "$dante_conf" "${dante_conf}.backup.$(date +%Y%m%d_%H%M%S)"
    fi
    
    # Create Dante configuration
    cat > "$dante_conf" <<EOF
# Auto-generated by auto-proxy-installer
# SOCKS5 Proxy Configuration

logoutput: /var/log/danted.log
internal: 0.0.0.0 port = $port
external: eth0
socksmethod: username
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error connect
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: connect
    log: error connect
    method: username
}
EOF
    
    # Open firewall port
    open_firewall_port "$port" "tcp"
    
    # Enable and start service
    systemctl daemon-reload
    systemctl enable danted
    if systemctl restart danted; then
        ok "Đã khởi động Dante service"
    else
        error "Không thể khởi động Dante service"
        error "Kiểm tra log: journalctl -u danted -n 50"
        return 1
    fi
    
    # Save state
    save_proxy_state "socks5" "$port" "$username" "$password"
    
    ok "SOCKS5 Proxy (Dante) đã được cài đặt thành công!"
    return 0
}

install_socks5_microsocks() {
    local port="$1"
    local username="$2"
    local password="$3"
    local pkg_manager="$4"
    
    info "Cài đặt SOCKS5 với microsocks..."
    
    # Check if we need to compile microsocks
    local microsocks_bin="/usr/local/bin/microsocks"
    local need_compile=true
    
    # Check if microsocks already exists
    if [ -f "$microsocks_bin" ] && [ -x "$microsocks_bin" ]; then
        info "microsocks đã có sẵn"
        need_compile=false
    fi
    
    if [ "$need_compile" = true ]; then
        # Install build dependencies
        local build_packages=()
        case "$pkg_manager" in
            apt|apt-get)
                build_packages=(build-essential git)
                ;;
            yum|dnf)
                build_packages=(gcc make git)
                ;;
        esac
        
        info "Đang cài đặt build dependencies..."
        install_packages "$pkg_manager" "${build_packages[@]}" || {
            error "Không thể cài đặt build dependencies"
            return 1
        }
        
        # Clone and compile microsocks
        local temp_dir=$(mktemp -d)
        cd "$temp_dir" || {
            error "Không thể tạo temp directory"
            return 1
        }
        
        info "Đang compile microsocks..."
        if git clone https://github.com/rofl0r/microsocks.git . >/dev/null 2>&1; then
            make >/dev/null 2>&1 || {
                error "Lỗi khi compile microsocks"
                cd - >/dev/null
                rm -rf "$temp_dir"
                return 1
            }
            
            if [ -f microsocks ]; then
                cp microsocks "$microsocks_bin"
                chmod +x "$microsocks_bin"
                ok "Đã compile và cài đặt microsocks"
            else
                error "Không tìm thấy binary sau khi compile"
                cd - >/dev/null
                rm -rf "$temp_dir"
                return 1
            fi
        else
            error "Không thể clone microsocks repository"
            cd - >/dev/null
            rm -rf "$temp_dir"
            return 1
        fi
        
        cd - >/dev/null
        rm -rf "$temp_dir"
    fi
    
    # Create password file
    local passwd_file="/etc/microsocks/passwd"
    mkdir -p "$(dirname "$passwd_file")"
    echo "$username:$password" > "$passwd_file"
    chmod 600 "$passwd_file"
    chown root:root "$passwd_file"
    
    # Create systemd service
    local service_file="/etc/systemd/system/microsocks.service"
    cat > "$service_file" <<EOF
[Unit]
Description=MicroSocks SOCKS5 Proxy Server
After=network.target

[Service]
Type=simple
User=nobody
ExecStart=$microsocks_bin -u $username -P $password -p $port
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
    
    # Open firewall port
    open_firewall_port "$port" "tcp"
    
    # Enable and start service
    systemctl daemon-reload
    systemctl enable microsocks
    if systemctl start microsocks; then
        sleep 2
        if systemctl is-active --quiet microsocks; then
            ok "Đã khởi động microsocks service"
        else
            error "microsocks service không chạy được"
            error "Kiểm tra log: journalctl -u microsocks -n 50"
            return 1
        fi
    else
        error "Không thể khởi động microsocks service"
        return 1
    fi
    
    # Save state
    save_proxy_state "socks5" "$port" "$username" "$password"
    
    ok "SOCKS5 Proxy (microsocks) đã được cài đặt thành công!"
    return 0
}

save_proxy_state() {
    local proxy_type="$1"
    local port="$2"
    local username="$3"
    local password="$4"
    
    local state_dir="/etc/auto-proxy-installer"
    mkdir -p "$state_dir"
    
    # Don't save password in state file
    local simple_state="$state_dir/installed_proxies.txt"
    echo "$proxy_type|$port|$username|$(date +%Y-%m-%d)" >> "$simple_state"
}

